package com.maybank.dataaccess.maybank.entity;

import java.io.Serializable;

public class TxnRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txn_record.txn_id
     *
     * @mbggenerated
     */
    private Integer txnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txn_record.account_number
     *
     * @mbggenerated
     */
    private String accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txn_record.trx_amount
     *
     * @mbggenerated
     */
    private Long trxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txn_record.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txn_record.trx_date
     *
     * @mbggenerated
     */
    private String trxDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txn_record.trx_time
     *
     * @mbggenerated
     */
    private String trxTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txn_record.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table txn_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txn_record.txn_id
     *
     * @return the value of txn_record.txn_id
     *
     * @mbggenerated
     */
    public Integer getTxnId() {
        return txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txn_record.txn_id
     *
     * @param txnId the value for txn_record.txn_id
     *
     * @mbggenerated
     */
    public void setTxnId(Integer txnId) {
        this.txnId = txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txn_record.account_number
     *
     * @return the value of txn_record.account_number
     *
     * @mbggenerated
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txn_record.account_number
     *
     * @param accountNumber the value for txn_record.account_number
     *
     * @mbggenerated
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txn_record.trx_amount
     *
     * @return the value of txn_record.trx_amount
     *
     * @mbggenerated
     */
    public Long getTrxAmount() {
        return trxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txn_record.trx_amount
     *
     * @param trxAmount the value for txn_record.trx_amount
     *
     * @mbggenerated
     */
    public void setTrxAmount(Long trxAmount) {
        this.trxAmount = trxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txn_record.description
     *
     * @return the value of txn_record.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txn_record.description
     *
     * @param description the value for txn_record.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txn_record.trx_date
     *
     * @return the value of txn_record.trx_date
     *
     * @mbggenerated
     */
    public String getTrxDate() {
        return trxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txn_record.trx_date
     *
     * @param trxDate the value for txn_record.trx_date
     *
     * @mbggenerated
     */
    public void setTrxDate(String trxDate) {
        this.trxDate = trxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txn_record.trx_time
     *
     * @return the value of txn_record.trx_time
     *
     * @mbggenerated
     */
    public String getTrxTime() {
        return trxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txn_record.trx_time
     *
     * @param trxTime the value for txn_record.trx_time
     *
     * @mbggenerated
     */
    public void setTrxTime(String trxTime) {
        this.trxTime = trxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txn_record.customer_id
     *
     * @return the value of txn_record.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txn_record.customer_id
     *
     * @param customerId the value for txn_record.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txn_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", txnId=").append(txnId);
        sb.append(", accountNumber=").append(accountNumber);
        sb.append(", trxAmount=").append(trxAmount);
        sb.append(", description=").append(description);
        sb.append(", trxDate=").append(trxDate);
        sb.append(", trxTime=").append(trxTime);
        sb.append(", customerId=").append(customerId);
        sb.append("]");
        return sb.toString();
    }
}